Prevent the pacman subprocess from receiving interruption signals from its parent, and kill signals from systemd
cmuench/pacman-auto-update pull request #12
Opened 2021-02-15 03:10 UTC by es20490446e

@cmuench Lately I have learned quite a lot about a variety of ways processes can be terminated, and how to prevent critical processes to be the target of that. There's plenty of tricky details about it, here's a summary:

=== DISABLING INTERRUPTION SIGNALS ===

Prevents the pacman subprocess from receiving interruptions sent to its parent, by running it on a different process group not connected to the same terminal. Still retaining their family hierarchy.

This prevents pacman to override the traps from its parent, and disallow pacman to be interrupted in the middle of an update. Otherwise pacman on an interruption would finish copying the current package files to the filesystem, but it will skip post-install operations and installing further packages.

Since packages are compiled against specific versions of their dependencies shared objects, that can render those packages broken. This can prevent the system from being bootable.

=== DISABLING KILL SIGNALS ===

The systemd unit was configured to send an interruption signal only to its parent process in the case of a reboot.

Explicitly setting that signal to be an interruption was useless. As by default systemd sends a termination signal, which is alike and equally handled in the code.

Still systemd by default will send a second kill signal if the process continues running after a certain period of time. This last kill signal has been disabled.

=== DECOUPLING DOWNLOADING FROM INSTALLING ===

The download of updates is done separately, and can be instantly interrupted. So if the user reboots, the waiting time for pacman-auto-update to finish will be lower.

=== AUTO-PRUNING THE CACHE ===

Packages in the cache three versions older than the current installed one will be automatically removed.

=== ONLY OUTPUTS ON ERROR ===

Only info that would require attendance by a human will be output, aka errors.

For debugging all input can be enabled by setting the variable "verbose=1".

=== REMOVE CREDITS ===

Who contributed to the project is already provided by GitHub itself, on the project front page.

The original code no longer looks as the one in this repository, and its' actually dangerous. Anyone using the code provided on the original tutorial, and rebooting their systems during an update, can end with an unbootable system.

2021-02-15 08:06 UTC, cmuench commented
@es20490446e wow. That's a big rewrite. Give me some time to check that on my machine.
Seems that you had fun. 😉

2021-02-15 11:05 UTC, es20490446e commented
The muse has come to my home and kissed me 😛

2021-02-15 13:08 UTC, cmuench requested changes
I like your code change, but please do not reduce the README all the time :-)

2021-02-15 21:31 UTC, es20490446e commented on README.md
> +## Description
Cause it's more regular, and I think having the name there really [doesn't matter™](https://signalvnoise.com/archives2/it_just_doesnt_matter.php).

We already know that we are reading Pacman Auto Update's readme, the software's name is already at the beginning of the page.

2021-02-16 16:43 UTC, cmuench commented on README.md
> +## Description
I totally disagree. It's the readme of the project which should start with the title of the project. That's common. See also other github repos.
For me it matters. It's also so that a document should should only one level 1 headline. That's also true for other documentation format. Please revert the documentation back.
I really like your technical change. Maybe the description of your pull request could be part of the readme file.

2021-02-16 20:33 UTC, es20490446e commented on README.md
> +## Description
I think that if someone wants to do things better than what is common, then what is common can no longer be the reference.

But about a header in a readme, I really don't care. You know 🤣

Also I think that the documentation shall explain what the software does, while leaving the how to the code itself. Making that code clear enough to be self explanatory.

2021-02-16 20:38 UTC, es20490446e commented on README.md
> +## Description
Brought back the title ✅

2021-02-16 20:39 UTC, cmuench commented on README.md
> +## Description
For this small project it's true. For bigger projects a good documentation is required.
I am managing a bigger open source project where a lot of useful stuff is written in the readme file.
For this small repository it's (currently) not required.
But everything big starts small...

2021-02-17 01:08 UTC, es20490446e commented on README.md
> +## Description
What I do is writing the smallest programs, then composing them to create new ones. So each program code by itself is the smallest it can be.

For instance I'm creating a derivative version of this software which is portable among distros. Just this small program already uses other three commands:

- so: for silencing command output while there are no errors.
- software: for installing packages on any Linux using the native package manager.
- waitFor: for avoiding a subprocess from being interrupted.

Then autoUpdate, the main program, will just be:

```
#! /bin/bash


mainFunction () {
	if ! connectionIsMetered; then
		software update
	fi
}


checkPermissions () {
	if [[ "$(id -u)" -ne 0 ]]; then
		sudo "${0}"
		exit "${?}"
	fi
}


connectionIsMetered () {
	[[ -f "/usr/bin/nmcli" ]] &&
	systemctl status NetworkManager | grep --quiet "running" &&
	nmcli --terse --fields GENERAL.METERED dev show | grep --quiet "yes"
}


prepareEnvironment () {
	set -eum
	trap "" ABRT ERR HUP INT QUIT TERM
	checkPermissions
}


prepareEnvironment
mainFunction
```

I do the same with documentation. I put it on a wiki, and separate it into the smallest sub-pages.

The documentation explains how to use the software, but never how it is developed. The coding style and size must be such that it is self explanatory.

2021-02-17 08:06 UTC, cmuench commented on README.md
> +## Description
Yes, that's not the point I disagree. Writing good readable code is important. If the functions are self-explaining. Great.
I am talking about bigger documentations. A good documentation is more than code documentation. That's not needed in this small project.
If you are interested. I am currently testing Antora/Asciidoc in combination with Arc42. https://arc42.org/
Arc42 is a way to structure the documentation. It's describe also a business context. Then you look on your software from outside and then drill down into the components.

2021-02-17 08:07 UTC, cmuench approved these changes

2021-02-17 08:07 UTC, merged

2021-02-17 09:09 UTC, es20490446e commented on README.md
> +## Description
Thanks for the suggestion. If I ever need to document a program, I will have a look at those.